preprocess:
  text_cleaner:
    cleaner_types: tacotron
  tokenizer:
    g2p_type: g2p_en_no_space
    token_type: phn
token:
  list:
  - <blank>
  - <unk>
  - AH0
  - N
  - T
  - D
  - S
  - R
  - L
  - DH
  - K
  - Z
  - IH1
  - IH0
  - M
  - EH1
  - W
  - P
  - AE1
  - AH1
  - V
  - ER0
  - F
  - ','
  - AA1
  - B
  - HH
  - IY1
  - UW1
  - IY0
  - AO1
  - EY1
  - AY1
  - .
  - OW1
  - SH
  - NG
  - G
  - ER1
  - CH
  - JH
  - Y
  - AW1
  - TH
  - UH1
  - EH2
  - OW0
  - EY2
  - AO0
  - IH2
  - AE2
  - AY2
  - AA2
  - UW0
  - EH0
  - OY1
  - EY0
  - AO2
  - ZH
  - OW2
  - AE0
  - UW2
  - AH2
  - AY0
  - IY2
  - AW2
  - AA0
  - ''''
  - ER2
  - UH2
  - '?'
  - OY2
  - '!'
  - AW0
  - UH0
  - OY0
  - ..
  - <sos/eos>
tts_model:
  model_path: 20220606_230202\full\tts_model.onnx
  model_type: VITS
